- name: Installing apitutude package and changing configuration in 50unattended-upgrade file
  hosts: all
  user: root
  tasks:
   - name: Install aptitude
     apt: name=aptitude update_cache=yes state=latest
   - name: Change configuration to send mail
     lineinfile: dest=/etc/apt/apt.conf.d/50unattended-upgrades regexp="^//Unattended-Upgrade::Mail "root"" line="Unattended-Upgrade::Mail "ashishbilawne@gmail.com";" state=present
   - name: Enable configuration to reboot false
     lineinfile: dest=/etc/apt/apt.conf.d/50unattended-upgrades regexp="^//Unattended-Upgrade::Automatic-Reboot "false"" line="Unattended-Upgrade::Automatic-Reboot "false";" state=present
